#include "init.h"

void GPIO_Ini(void){
    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOCEN); //Power on B and C ports

    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE7_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_7);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR7_0);
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR7_0);

    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODE13_0 | GPIO_MODER_MODE13_1);
    CLEAR_BIT(GPIOC->OTYPER, GPIO_OTYPER_OT_13);
    SET_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEEDR13_0);
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR13_0);
}